kind: pipeline
type: kubernetes
name: default
metadata:
  namespace: gitea
steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: release
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    environment:
      GITEA_URL:
        from_secret: gitea_url
      GITEA_TOKEN:
        from_secret: gitea_token
      AWS_ACCESS_KEY_ID:
        from_secret: s3_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: s3_key
      S3_BUCKET:
        from_secret: s3_bucket
      S3_REGION:
        from_secret: s3_region
      S3_ENDPOINT:
        from_secret: s3_endpoint
trigger:
  event:
  - tag

