project_name: 'librespeed-cli'
#dist: ./out
before:
  hooks:
    - go mod download
builds:
- main: ./main.go
  env:
  - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - -w -s -X "librespeed-cli/defs.ProgName={{ .ProjectName }}" -X "librespeed-cli/defs.ProgVersion=v{{ .Version }}" -X "librespeed-cli/defs.BuildDate={{ .Date }}"
  goos:
    - windows
    - linux
    - darwin
    - freebsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
    - mips
    - mipsle
    - mips64
    - mips64le
  goarm:
    - 5
    - 6
    - 7
  gomips:
    - hardfloat
    - softfloat
  ignore:
    - goos: darwin
      goarch: 386
  hooks:
    post: ./upx.sh
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: false
  sort: asc
brews:
  - github:
      owner: librespeed
      name: homebrew-tap
    commit_author:
      name: "Maddie Zhan"
      email: maddie.zhan@gmail.com
    folder: Formula
    homepage: "https://github.com/librespeed/speedtest-cli"
    description: "Command-line client for LibreSpeed"
    skip_upload: true
    custom_block: |
      head "https://github.com/librespeed/speedtest-cli.git"
release:
  github:
    owner: librespeed
    name: speedtest-cli
  disable: false
